In [95]:
#import yaml
#from twitter_keys import search_tweets_api

#print(yaml.dump(yaml.load(search_tweets_api)))


#!pip install protobuf
#!pip install PyHamcrest
#!pip install langdetect

Collecting protobuf
  Downloading https://files.pythonhosted.org/packages/77/78/a7f1ce761e2c738e209857175cd4f90a8562d1bde32868a8cd5290d58926/protobuf-3.6.1-py2.py3-none-any.whl (390kB)
Requirement already satisfied: setuptools in c:\users\deborah aina\appdata\local\continuum\anaconda3\lib\site-packages (from protobuf) (40.2.0)
Requirement already satisfied: six>=1.9 in c:\users\deborah aina\appdata\local\continuum\anaconda3\lib\site-packages (from protobuf) (1.11.0)
Installing collected packages: protobuf
Successfully installed protobuf-3.6.1
Requirement already satisfied: PyHamcrest in c:\users\deborah aina\appdata\local\continuum\anaconda3\lib\site-packages (1.9.0)
Requirement already satisfied: six in c:\users\deborah aina\appdata\local\continuum\anaconda3\lib\site-packages (from PyHamcrest) (1.11.0)
Requirement already satisfied: setuptools in c:\users\deborah aina\appdata\local\continuum\anaconda3\lib\site-packages (from PyHamcrest) (40.2.0)
Requirement already satisfied: langdetect in c:\users\deborah aina\appdata\local\continuum\anaconda3\lib\site-packages (1.0.7)
Requirement already satisfied: six in c:\users\deborah aina\appdata\local\continuum\anaconda3\lib\site-packages (from langdetect) (1.11.0)

In [3]:
#__future__ is a pseudo-module which programmers can use to enable new 
#language features which are not compatible with the current interpreter
from __future__ import print_function

#Base64 converts a string of bytes into a string of ASCII characters so that they 
#can be safely transmitted within HTTP headers. A byte consist of 8 bits
import base64
import requests
import urllib.parse

OAUTH2_TOKEN = 'https://api.twitter.com/oauth2/token'


def get_bearer_token(consumer_key, consumer_secret):
    # enconde consumer key
    consumer_key = urllib.parse.quote(consumer_key)
    # encode consumer secret
    consumer_secret = urllib.parse.quote(consumer_secret)
    # create bearer token
    bearer_token = consumer_key + ':' + consumer_secret
    # base64 encode the token
    base64_encoded_bearer_token = base64.b64encode(bearer_token.encode('utf-8'))
    # set headers
    headers = {
        "Authorization": "Basic " + base64_encoded_bearer_token.decode('utf-8') + "",
        "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
        "Content-Length": "29"}

    response = requests.post(OAUTH2_TOKEN, headers=headers, data={'grant_type': 'client_credentials'})
    to_json = response.json()
    print("token_type = %s\naccess_token  = %s" % (to_json["token_type"], to_json['access_token']))


def main():
    consumer_key = input('Enter your consumer key: ')
    consumer_secret = input('Enter your consumer secret: ')
    print("***** ***** ***** *****")
    get_bearer_token(consumer_key, consumer_secret)


if __name__ == "__main__":
    main()

Enter your consumer key: DXuVL5LsOnE0jrsZJCbcns7Zu
Enter your consumer secret: Iu2j1kdm2UwxtnJi6sNsITYSgq8OO6GxlPsRcUEqz9cMmvLML6
***** ***** ***** *****
token_type = bearer
access_token  = AAAAAAAAAAAAAAAAAAAAAHJO9QAAAAAA1lq7WQQXLvjx4lLluLiFHkQ2J7s%3DjEgVHHSiliXi4wJg5xQ4yh5N2UneNteevNBkMbhcxZ7IYoJ1Vm

In [92]:
#premium_search_args = load_credentials(filename="/.twitter_keys.ymal",
                                       #yaml_key="search_tweets_api",
                                       #env_overwrite=False)

from searchtweets import collect_results
rule = gen_rule_payload("tornado",
                        "from:weatherchannel",
                        from_date="2012-01-01",
                        to_date="2012-01-03")
tweets = collect_results(rule,
                         500,
                         {
                             'bearer_token':"AAAAAAAAAAAAAAAAAAAAAHJO9QAAAAAA1lq7WQQXLvjx4lLluLiFHkQ2J7s%3DjEgVHHSiliXi4wJg5xQ4yh5N2UneNteevNBkMbhcxZ7IYoJ1Vm",
                             'endpoint':"https://api.twitter.com/1.1/tweets/search/fullarchive/Plongterm.json",
                             'account_type':"premium"
                         })
[print(tweet.all_text, end='\n\n') for tweet in tweets[0:20]];
#{#query="from:weatherchannel lang:en keyword:tornado has:media",
                        #from_date="2012-01-01",
                        #to_date="2012-01-03"}

A tornado flew around my room before you came.

Vivencia no exterior tem se tornado um grande diferencial nos processos seletivos. Vale a ena investir nisso.

Mapleton Upgrading After Tornado - WOWT: It's been almost nine months since a tornado hit Mapleton, Iow... http://t.co/xfEODRaa #tornado

Sem duvida nenhuma eu posso dizer que sem vcs a novela não teria se tornado o que se tornou, vcs são INCRÍVEIS!!

Só lamento por você ter se tornado essa pessoa. SÉRIO, SÓ LAMENTO.

Adoro o facto do Twitter se ter tornado numa fonte fidedigna de informação :D

pessoas que entram e saem de nossas vidas como se fossem um tornado de sentimentos, que devasta e marca tudo por onde passa.

Iya emg kan wkw RT @ninanf: Gtw :3 eh put tornado nyeremin bgt yacchhh x("@Pupuuuttt: Apasih? --a RT @ninanf Knp putttt?"

TENÉS QUE SER VIVO BOLUDO MIRÁ SI VAS A USAR CASCO???... si te vas a matar en una tornado hacelo con estilo no?... #pajero

Yo wats good this baby tornado outside 

My room looks like a tornado hit #gottaclean

Hbd salaz tornado &lt;=-p @salazpro

#hurricane: Joplin Tornado, Lisa Irwin Among Top Missouri Stories in 2011 (ContributorNetwork) http://t.co/J3x5IyoZ

União Europeia, um sonho Nazi tornado realidade http://t.co/R1H0q2Ze

Estoy por subir una foto de mi gata a Tumblr y desatar un tornado.

Hey East Bay! On Friday, before you head over to our show with Kevin Seconds, Tornado Rider, Emily's Army and The... http://t.co/72u8P0Wv

Mapleton Upgrading After Tornado - It's been almost nine months since a tornado hit Mapleton, Iowa on April 9, 20... http://t.co/jS6fE1Jq

A tornado flew around my room before you came...

RT @pabloportillo: tornado contra @luiscarlosma @GloriaAura @andyescalona  http://t.co/q8jNmDf6 // chequen el video y lo q nos paso :'( jaja

Got so much done today! My room looked like a tornado went through itt. Finally got stuff back in its proper place :) ahhh relieved

In [47]:
[print(tweet.created_at_datetime) for tweet in tweets[0:15]];

2017-12-30 23:59:46
2017-12-30 23:59:46
2017-12-30 23:59:29
2017-12-30 23:58:45
2017-12-30 23:58:17
2017-12-30 23:58:16
2017-12-30 23:57:39
2017-12-30 23:56:49
2017-12-30 23:56:49
2017-12-30 23:55:17
2017-12-30 23:55:14
2017-12-30 23:55:05
2017-12-30 23:55:03
2017-12-30 23:54:54
2017-12-30 23:54:44

In [48]:
from searchtweets import collect_results
rule = gen_rule_payload("from:weatherchannel",
                        from_date="2012-01-01",
                        to_date="2017-12-31",
                        count_bucket="day",
                        results_per_call=500)
print(rule)
{"query":"from:weatherchannel","toDate":"201201010000","fromDate":"201712310000","bucket":"day"}

counts = collect_results(rule,
                         500,
                         {
                             'bearer_token':"AAAAAAAAAAAAAAAAAAAAAHJO9QAAAAAA1lq7WQQXLvjx4lLluLiFHkQ2J7s%3DjEgVHHSiliXi4wJg5xQ4yh5N2UneNteevNBkMbhcxZ7IYoJ1Vm",
                             'endpoint':"https://api.twitter.com/1.1/tweets/search/fullarchive/Plongterm.json",
                             'account_type':"premium"
                         })
[print(tweet.all_text, end='\n\n') for tweet in tweets[0:10]];

[print(c) for c in counts];

{"query": "from:weatherchannel", "toDate": "201712310000", "fromDate": "201201010000", "bucket": "day"}

retrying request; current status code: 429

2811 tornado warnings were issued by local forecast offices in 2017. #weatherOf2017
Learn more about tornadoes: https://t.co/N0C7rm48ne https://t.co/G28DBrQ9e2

Sonic Unleashed (X360/PS3) | Part 40: Hub World Stuff &amp; Tornado Stage 2: https://t.co/lfjSKVS5FC via @YouTube

I added a video to a @YouTube playlist https://t.co/lfjSKVS5FC Sonic Unleashed (X360/PS3) | Part 40: Hub World Stuff &amp; Tornado Stage 2

These lads are looking forward to kicking off the 5th Anniversary year.

Join us on 22nd of April when they encounter a Tornado!

@60163_Tornado  / @midrlybutterley https://t.co/qhIDLmqPDA

2811 tornado warnings were issued by local forecast offices in 2017. #weatherOf2017
Learn more about tornadoes: https://t.co/N0C7rm48ne https://t.co/G28DBrQ9e2

When you try to grab a hold of me while on tornado mode @dAmAgEeFFeCt  https://t.co/N5oVN6LFOc

“One year out, this may be Trump’s greatest trick: His tornado of news-making has scrambled Americans’ grasp of time &amp; memory, producing...sensory overload that can make even seismic events...disappear from the collective consciousness &amp; public view.” https://t.co/pHAweJbaru

Muzikálový hit Největší showman vrazil do kin jak tornádo. Už jste ho viděli? Co na něj říkáte?
https://t.co/HLjHXuyw2T

2811 tornado warnings were issued by local forecast offices in 2017. #weatherOf2017
Learn more about tornadoes: https://t.co/N0C7rm48ne https://t.co/G28DBrQ9e2

Adicionei um vídeo a uma lista de reprodução do @YouTube https://t.co/1YIQHzVkrd CLOSE VIOLENT TORNADO SOUND !!! Coleridge, NE

{'timePeriod': '201711300000', 'count': 43}
{'timePeriod': '201712010000', 'count': 39}
{'timePeriod': '201712020000', 'count': 23}
{'timePeriod': '201712030000', 'count': 20}
{'timePeriod': '201712040000', 'count': 34}
{'timePeriod': '201712050000', 'count': 68}
{'timePeriod': '201712060000', 'count': 47}
{'timePeriod': '201712070000', 'count': 49}
{'timePeriod': '201712080000', 'count': 117}
{'timePeriod': '201712090000', 'count': 13}
{'timePeriod': '201712100000', 'count': 26}
{'timePeriod': '201712110000', 'count': 32}
{'timePeriod': '201712120000', 'count': 35}
{'timePeriod': '201712130000', 'count': 35}
{'timePeriod': '201712140000', 'count': 33}
{'timePeriod': '201712150000', 'count': 36}
{'timePeriod': '201712160000', 'count': 16}
{'timePeriod': '201712170000', 'count': 15}
{'timePeriod': '201712180000', 'count': 35}
{'timePeriod': '201712190000', 'count': 28}
{'timePeriod': '201712200000', 'count': 41}
{'timePeriod': '201712210000', 'count': 46}
{'timePeriod': '201712220000', 'count': 25}
{'timePeriod': '201712230000', 'count': 22}
{'timePeriod': '201712240000', 'count': 15}
{'timePeriod': '201712250000', 'count': 27}
{'timePeriod': '201712260000', 'count': 24}
{'timePeriod': '201712270000', 'count': 20}
{'timePeriod': '201712280000', 'count': 37}
{'timePeriod': '201712290000', 'count': 33}
{'timePeriod': '201712300000', 'count': 21}
{'timePeriod': '201710300000', 'count': 56}
{'timePeriod': '201710310000', 'count': 35}
{'timePeriod': '201711010000', 'count': 41}
{'timePeriod': '201711020000', 'count': 22}
{'timePeriod': '201711030000', 'count': 21}
{'timePeriod': '201711040000', 'count': 12}
{'timePeriod': '201711050000', 'count': 29}
{'timePeriod': '201711060000', 'count': 28}
{'timePeriod': '201711070000', 'count': 34}
{'timePeriod': '201711080000', 'count': 30}
{'timePeriod': '201711090000', 'count': 38}
{'timePeriod': '201711100000', 'count': 28}
{'timePeriod': '201711110000', 'count': 16}
{'timePeriod': '201711120000', 'count': 28}
{'timePeriod': '201711130000', 'count': 33}
{'timePeriod': '201711140000', 'count': 20}
{'timePeriod': '201711150000', 'count': 27}
{'timePeriod': '201711160000', 'count': 26}
{'timePeriod': '201711170000', 'count': 26}
{'timePeriod': '201711180000', 'count': 21}
{'timePeriod': '201711190000', 'count': 28}
{'timePeriod': '201711200000', 'count': 27}
{'timePeriod': '201711210000', 'count': 29}
{'timePeriod': '201711220000', 'count': 11}
{'timePeriod': '201711230000', 'count': 8}
{'timePeriod': '201711240000', 'count': 10}
{'timePeriod': '201711250000', 'count': 6}
{'timePeriod': '201711260000', 'count': 9}
{'timePeriod': '201711270000', 'count': 62}
{'timePeriod': '201711280000', 'count': 46}
{'timePeriod': '201711290000', 'count': 32}
{'timePeriod': '201709290000', 'count': 18}
{'timePeriod': '201709300000', 'count': 10}
{'timePeriod': '201710010000', 'count': 12}
{'timePeriod': '201710020000', 'count': 29}
{'timePeriod': '201710030000', 'count': 28}
{'timePeriod': '201710040000', 'count': 42}
{'timePeriod': '201710050000', 'count': 97}
{'timePeriod': '201710060000', 'count': 91}
{'timePeriod': '201710070000', 'count': 62}
{'timePeriod': '201710080000', 'count': 94}
{'timePeriod': '201710090000', 'count': 76}
{'timePeriod': '201710100000', 'count': 43}
{'timePeriod': '201710110000', 'count': 44}
{'timePeriod': '201710120000', 'count': 26}
{'timePeriod': '201710130000', 'count': 30}
{'timePeriod': '201710140000', 'count': 24}
{'timePeriod': '201710150000', 'count': 17}
{'timePeriod': '201710160000', 'count': 53}
{'timePeriod': '201710170000', 'count': 23}
{'timePeriod': '201710180000', 'count': 45}
{'timePeriod': '201710190000', 'count': 32}
{'timePeriod': '201710200000', 'count': 26}
{'timePeriod': '201710210000', 'count': 16}
{'timePeriod': '201710220000', 'count': 21}
{'timePeriod': '201710230000', 'count': 43}
{'timePeriod': '201710240000', 'count': 35}
{'timePeriod': '201710250000', 'count': 25}
{'timePeriod': '201710260000', 'count': 55}
{'timePeriod': '201710270000', 'count': 37}
{'timePeriod': '201710280000', 'count': 17}
{'timePeriod': '201710290000', 'count': 20}
{'timePeriod': '201708290000', 'count': 113}
{'timePeriod': '201708300000', 'count': 85}
{'timePeriod': '201708310000', 'count': 183}
{'timePeriod': '201709010000', 'count': 81}
{'timePeriod': '201709020000', 'count': 25}
{'timePeriod': '201709030000', 'count': 13}
{'timePeriod': '201709040000', 'count': 23}
{'timePeriod': '201709050000', 'count': 63}
{'timePeriod': '201709060000', 'count': 85}
{'timePeriod': '201709070000', 'count': 80}
{'timePeriod': '201709080000', 'count': 54}
{'timePeriod': '201709090000', 'count': 86}
{'timePeriod': '201709100000', 'count': 145}
{'timePeriod': '201709110000', 'count': 114}
{'timePeriod': '201709120000', 'count': 59}
{'timePeriod': '201709130000', 'count': 22}
{'timePeriod': '201709140000', 'count': 26}
{'timePeriod': '201709150000', 'count': 34}
{'timePeriod': '201709160000', 'count': 13}
{'timePeriod': '201709170000', 'count': 17}
{'timePeriod': '201709180000', 'count': 45}
{'timePeriod': '201709190000', 'count': 111}
{'timePeriod': '201709200000', 'count': 86}
{'timePeriod': '201709210000', 'count': 57}
{'timePeriod': '201709220000', 'count': 37}
{'timePeriod': '201709230000', 'count': 36}
{'timePeriod': '201709240000', 'count': 18}
{'timePeriod': '201709250000', 'count': 25}
{'timePeriod': '201709260000', 'count': 40}
{'timePeriod': '201709270000', 'count': 30}
{'timePeriod': '201709280000', 'count': 35}
{'timePeriod': '201707290000', 'count': 26}
{'timePeriod': '201707300000', 'count': 17}
{'timePeriod': '201707310000', 'count': 43}
{'timePeriod': '201708010000', 'count': 31}
{'timePeriod': '201708020000', 'count': 39}
{'timePeriod': '201708030000', 'count': 34}
{'timePeriod': '201708040000', 'count': 37}
{'timePeriod': '201708050000', 'count': 17}
{'timePeriod': '201708060000', 'count': 38}
{'timePeriod': '201708070000', 'count': 56}
{'timePeriod': '201708080000', 'count': 58}
{'timePeriod': '201708090000', 'count': 27}
{'timePeriod': '201708100000', 'count': 45}
{'timePeriod': '201708110000', 'count': 21}
{'timePeriod': '201708120000', 'count': 32}
{'timePeriod': '201708130000', 'count': 26}
{'timePeriod': '201708140000', 'count': 33}
{'timePeriod': '201708150000', 'count': 36}
{'timePeriod': '201708160000', 'count': 41}
{'timePeriod': '201708170000', 'count': 39}
{'timePeriod': '201708180000', 'count': 43}
{'timePeriod': '201708190000', 'count': 39}
{'timePeriod': '201708200000', 'count': 24}
{'timePeriod': '201708210000', 'count': 100}
{'timePeriod': '201708220000', 'count': 48}
{'timePeriod': '201708230000', 'count': 38}
{'timePeriod': '201708240000', 'count': 72}
{'timePeriod': '201708250000', 'count': 140}
{'timePeriod': '201708260000', 'count': 209}
{'timePeriod': '201708270000', 'count': 363}
{'timePeriod': '201708280000', 'count': 164}
{'timePeriod': '201706280000', 'count': 79}
{'timePeriod': '201706290000', 'count': 72}
{'timePeriod': '201706300000', 'count': 24}
{'timePeriod': '201707010000', 'count': 23}
{'timePeriod': '201707020000', 'count': 13}
{'timePeriod': '201707030000', 'count': 16}
{'timePeriod': '201707040000', 'count': 20}
{'timePeriod': '201707050000', 'count': 21}
{'timePeriod': '201707060000', 'count': 57}
{'timePeriod': '201707070000', 'count': 44}
{'timePeriod': '201707080000', 'count': 22}
{'timePeriod': '201707090000', 'count': 14}
{'timePeriod': '201707100000', 'count': 60}
{'timePeriod': '201707110000', 'count': 56}
{'timePeriod': '201707120000', 'count': 37}
{'timePeriod': '201707130000', 'count': 48}
{'timePeriod': '201707140000', 'count': 23}
{'timePeriod': '201707150000', 'count': 43}
{'timePeriod': '201707160000', 'count': 17}
{'timePeriod': '201707170000', 'count': 30}
{'timePeriod': '201707180000', 'count': 23}
{'timePeriod': '201707190000', 'count': 31}
{'timePeriod': '201707200000', 'count': 52}
{'timePeriod': '201707210000', 'count': 32}
{'timePeriod': '201707220000', 'count': 30}
{'timePeriod': '201707230000', 'count': 26}
{'timePeriod': '201707240000', 'count': 32}
{'timePeriod': '201707250000', 'count': 25}
{'timePeriod': '201707260000', 'count': 32}
{'timePeriod': '201707270000', 'count': 38}
{'timePeriod': '201707280000', 'count': 43}
{'timePeriod': '201705280000', 'count': 52}
{'timePeriod': '201705290000', 'count': 24}
{'timePeriod': '201705300000', 'count': 24}
{'timePeriod': '201705310000', 'count': 21}
{'timePeriod': '201706010000', 'count': 19}
{'timePeriod': '201706020000', 'count': 17}
{'timePeriod': '201706030000', 'count': 13}
{'timePeriod': '201706040000', 'count': 14}
{'timePeriod': '201706050000', 'count': 11}
{'timePeriod': '201706060000', 'count': 18}
{'timePeriod': '201706070000', 'count': 29}
{'timePeriod': '201706080000', 'count': 22}
{'timePeriod': '201706090000', 'count': 15}
{'timePeriod': '201706100000', 'count': 21}
{'timePeriod': '201706110000', 'count': 22}
{'timePeriod': '201706120000', 'count': 57}
{'timePeriod': '201706130000', 'count': 69}
{'timePeriod': '201706140000', 'count': 47}
{'timePeriod': '201706150000', 'count': 37}
{'timePeriod': '201706160000', 'count': 36}
{'timePeriod': '201706170000', 'count': 39}
{'timePeriod': '201706180000', 'count': 19}
{'timePeriod': '201706190000', 'count': 60}
{'timePeriod': '201706200000', 'count': 43}
{'timePeriod': '201706210000', 'count': 90}
{'timePeriod': '201706220000', 'count': 88}
{'timePeriod': '201706230000', 'count': 50}
{'timePeriod': '201706240000', 'count': 20}
{'timePeriod': '201706250000', 'count': 25}
{'timePeriod': '201706260000', 'count': 32}
{'timePeriod': '201706270000', 'count': 24}
{'timePeriod': '201704270000', 'count': 38}
{'timePeriod': '201704280000', 'count': 11}
{'timePeriod': '201704290000', 'count': 28}
{'timePeriod': '201704300000', 'count': 22}
{'timePeriod': '201705010000', 'count': 22}
{'timePeriod': '201705020000', 'count': 18}
{'timePeriod': '201705030000', 'count': 37}
{'timePeriod': '201705040000', 'count': 25}
{'timePeriod': '201705050000', 'count': 53}
{'timePeriod': '201705060000', 'count': 18}
{'timePeriod': '201705070000', 'count': 12}
{'timePeriod': '201705080000', 'count': 13}
{'timePeriod': '201705090000', 'count': 30}
{'timePeriod': '201705100000', 'count': 41}
{'timePeriod': '201705110000', 'count': 42}
{'timePeriod': '201705120000', 'count': 27}
{'timePeriod': '201705130000', 'count': 16}
{'timePeriod': '201705140000', 'count': 12}
{'timePeriod': '201705150000', 'count': 16}
{'timePeriod': '201705160000', 'count': 50}
{'timePeriod': '201705170000', 'count': 62}
{'timePeriod': '201705180000', 'count': 76}
{'timePeriod': '201705190000', 'count': 90}
{'timePeriod': '201705200000', 'count': 44}
{'timePeriod': '201705210000', 'count': 13}
{'timePeriod': '201705220000', 'count': 14}
{'timePeriod': '201705230000', 'count': 58}
{'timePeriod': '201705240000', 'count': 33}
{'timePeriod': '201705250000', 'count': 25}
{'timePeriod': '201705260000', 'count': 21}
{'timePeriod': '201705270000', 'count': 63}
{'timePeriod': '201703270000', 'count': 57}
{'timePeriod': '201703280000', 'count': 36}
{'timePeriod': '201703290000', 'count': 43}
{'timePeriod': '201703300000', 'count': 28}
{'timePeriod': '201703310000', 'count': 23}
{'timePeriod': '201704010000', 'count': 8}
{'timePeriod': '201704020000', 'count': 20}
{'timePeriod': '201704030000', 'count': 50}
{'timePeriod': '201704040000', 'count': 22}
{'timePeriod': '201704050000', 'count': 98}
{'timePeriod': '201704060000', 'count': 42}
{'timePeriod': '201704070000', 'count': 12}
{'timePeriod': '201704080000', 'count': 9}
{'timePeriod': '201704090000', 'count': 14}
{'timePeriod': '201704100000', 'count': 19}
{'timePeriod': '201704110000', 'count': 22}
{'timePeriod': '201704120000', 'count': 14}
{'timePeriod': '201704130000', 'count': 23}
{'timePeriod': '201704140000', 'count': 19}
{'timePeriod': '201704150000', 'count': 19}
{'timePeriod': '201704160000', 'count': 22}
{'timePeriod': '201704170000', 'count': 23}
{'timePeriod': '201704180000', 'count': 17}
{'timePeriod': '201704190000', 'count': 23}
{'timePeriod': '201704200000', 'count': 29}
{'timePeriod': '201704210000', 'count': 28}
{'timePeriod': '201704220000', 'count': 38}
{'timePeriod': '201704230000', 'count': 14}
{'timePeriod': '201704240000', 'count': 18}
{'timePeriod': '201704250000', 'count': 18}
{'timePeriod': '201704260000', 'count': 36}
{'timePeriod': '201702240000', 'count': 22}
{'timePeriod': '201702250000', 'count': 25}
{'timePeriod': '201702260000', 'count': 15}
{'timePeriod': '201702270000', 'count': 18}
{'timePeriod': '201702280000', 'count': 45}
{'timePeriod': '201703010000', 'count': 153}
{'timePeriod': '201703020000', 'count': 29}
{'timePeriod': '201703030000', 'count': 14}
{'timePeriod': '201703040000', 'count': 13}
{'timePeriod': '201703050000', 'count': 15}
{'timePeriod': '201703060000', 'count': 36}
{'timePeriod': '201703070000', 'count': 113}
{'timePeriod': '201703080000', 'count': 24}
{'timePeriod': '201703090000', 'count': 25}
{'timePeriod': '201703100000', 'count': 52}
{'timePeriod': '201703110000', 'count': 14}
{'timePeriod': '201703120000', 'count': 17}
{'timePeriod': '201703130000', 'count': 36}
{'timePeriod': '201703140000', 'count': 48}
{'timePeriod': '201703150000', 'count': 20}
{'timePeriod': '201703160000', 'count': 23}
{'timePeriod': '201703170000', 'count': 25}
{'timePeriod': '201703180000', 'count': 8}
{'timePeriod': '201703190000', 'count': 10}
{'timePeriod': '201703200000', 'count': 18}
{'timePeriod': '201703210000', 'count': 27}
{'timePeriod': '201703220000', 'count': 15}
{'timePeriod': '201703230000', 'count': 11}
{'timePeriod': '201703240000', 'count': 12}
{'timePeriod': '201703250000', 'count': 29}
{'timePeriod': '201703260000', 'count': 28}
{'timePeriod': '201701240000', 'count': 23}
{'timePeriod': '201701250000', 'count': 18}
{'timePeriod': '201701260000', 'count': 15}
{'timePeriod': '201701270000', 'count': 15}
{'timePeriod': '201701280000', 'count': 9}
{'timePeriod': '201701290000', 'count': 17}
{'timePeriod': '201701300000', 'count': 23}
{'timePeriod': '201701310000', 'count': 13}
{'timePeriod': '201702010000', 'count': 21}
{'timePeriod': '201702020000', 'count': 16}
{'timePeriod': '201702030000', 'count': 14}
{'timePeriod': '201702040000', 'count': 14}
{'timePeriod': '201702050000', 'count': 21}
{'timePeriod': '201702060000', 'count': 19}
{'timePeriod': '201702070000', 'count': 82}
{'timePeriod': '201702080000', 'count': 35}
{'timePeriod': '201702090000', 'count': 61}
{'timePeriod': '201702100000', 'count': 21}
{'timePeriod': '201702110000', 'count': 11}
{'timePeriod': '201702120000', 'count': 17}
{'timePeriod': '201702130000', 'count': 20}
{'timePeriod': '201702140000', 'count': 41}
{'timePeriod': '201702150000', 'count': 30}
{'timePeriod': '201702160000', 'count': 31}
{'timePeriod': '201702170000', 'count': 37}
{'timePeriod': '201702180000', 'count': 12}
{'timePeriod': '201702190000', 'count': 20}
{'timePeriod': '201702200000', 'count': 33}
{'timePeriod': '201702210000', 'count': 28}
{'timePeriod': '201702220000', 'count': 18}
{'timePeriod': '201702230000', 'count': 17}
{'timePeriod': '201612240000', 'count': 14}
{'timePeriod': '201612250000', 'count': 14}
{'timePeriod': '201612260000', 'count': 14}
{'timePeriod': '201612270000', 'count': 15}
{'timePeriod': '201612280000', 'count': 19}
{'timePeriod': '201612290000', 'count': 21}
{'timePeriod': '201612300000', 'count': 18}
{'timePeriod': '201612310000', 'count': 17}
{'timePeriod': '201701010000', 'count': 16}
{'timePeriod': '201701020000', 'count': 42}
{'timePeriod': '201701030000', 'count': 36}
{'timePeriod': '201701040000', 'count': 30}
{'timePeriod': '201701050000', 'count': 26}
{'timePeriod': '201701060000', 'count': 30}
{'timePeriod': '201701070000', 'count': 29}
{'timePeriod': '201701080000', 'count': 10}
{'timePeriod': '201701090000', 'count': 19}
{'timePeriod': '201701100000', 'count': 22}
{'timePeriod': '201701110000', 'count': 16}
{'timePeriod': '201701120000', 'count': 23}
{'timePeriod': '201701130000', 'count': 26}
{'timePeriod': '201701140000', 'count': 17}
{'timePeriod': '201701150000', 'count': 23}
{'timePeriod': '201701160000', 'count': 36}
{'timePeriod': '201701170000', 'count': 19}
{'timePeriod': '201701180000', 'count': 28}
{'timePeriod': '201701190000', 'count': 24}
{'timePeriod': '201701200000', 'count': 21}
{'timePeriod': '201701210000', 'count': 96}
{'timePeriod': '201701220000', 'count': 174}
{'timePeriod': '201701230000', 'count': 37}
{'timePeriod': '201611230000', 'count': 27}
{'timePeriod': '201611240000', 'count': 15}
{'timePeriod': '201611250000', 'count': 7}
{'timePeriod': '201611260000', 'count': 8}
{'timePeriod': '201611270000', 'count': 10}
{'timePeriod': '201611280000', 'count': 31}
{'timePeriod': '201611290000', 'count': 54}
{'timePeriod': '201611300000', 'count': 134}
{'timePeriod': '201612010000', 'count': 29}
{'timePeriod': '201612020000', 'count': 21}
{'timePeriod': '201612030000', 'count': 14}
{'timePeriod': '201612040000', 'count': 19}
{'timePeriod': '201612050000', 'count': 21}
{'timePeriod': '201612060000', 'count': 21}
{'timePeriod': '201612070000', 'count': 19}
{'timePeriod': '201612080000', 'count': 32}
{'timePeriod': '201612090000', 'count': 16}
{'timePeriod': '201612100000', 'count': 8}
{'timePeriod': '201612110000', 'count': 17}
{'timePeriod': '201612120000', 'count': 21}
{'timePeriod': '201612130000', 'count': 23}
{'timePeriod': '201612140000', 'count': 20}
{'timePeriod': '201612150000', 'count': 25}
{'timePeriod': '201612160000', 'count': 27}
{'timePeriod': '201612170000', 'count': 31}
{'timePeriod': '201612180000', 'count': 29}
{'timePeriod': '201612190000', 'count': 21}
{'timePeriod': '201612200000', 'count': 12}
{'timePeriod': '201612210000', 'count': 27}
{'timePeriod': '201612220000', 'count': 20}
{'timePeriod': '201612230000', 'count': 20}
{'timePeriod': '201610230000', 'count': 11}
{'timePeriod': '201610240000', 'count': 24}
{'timePeriod': '201610250000', 'count': 24}
{'timePeriod': '201610260000', 'count': 23}
{'timePeriod': '201610270000', 'count': 31}
{'timePeriod': '201610280000', 'count': 22}
{'timePeriod': '201610290000', 'count': 10}
{'timePeriod': '201610300000', 'count': 12}
{'timePeriod': '201610310000', 'count': 25}
{'timePeriod': '201611010000', 'count': 27}
{'timePeriod': '201611020000', 'count': 31}
{'timePeriod': '201611030000', 'count': 28}
{'timePeriod': '201611040000', 'count': 18}
{'timePeriod': '201611050000', 'count': 11}
{'timePeriod': '201611060000', 'count': 11}
{'timePeriod': '201611070000', 'count': 22}

In [113]:
import pandas as pd

counts_df = pd.DataFrame(counts)

counts_df.head(1000)

counts_df["Tweet_Date"] = pd.to_datetime(counts_df["timePeriod"], format="%Y%m%d%H%M", errors='ignore')

counts_df.head(100)

    count    timePeriod Tweet_Date
0      20  201711300000 2017-11-30
1      19  201712010000 2017-12-01
2      21  201712020000 2017-12-02
3      24  201712030000 2017-12-03
4      21  201712040000 2017-12-04
5      25  201712050000 2017-12-05
6      21  201712060000 2017-12-06
7      23  201712070000 2017-12-07
8      21  201712080000 2017-12-08
9      24  201712090000 2017-12-09
10     22  201712100000 2017-12-10
11     22  201712110000 2017-12-11
12     22  201712120000 2017-12-12
13     19  201712130000 2017-12-13
14     18  201712140000 2017-12-14
15     19  201712150000 2017-12-15
16     24  201712160000 2017-12-16
17     22  201712170000 2017-12-17
18     21  201712180000 2017-12-18
19     18  201712190000 2017-12-19
20     19  201712200000 2017-12-20
21     20  201712210000 2017-12-21
22     19  201712220000 2017-12-22
23     22  201712230000 2017-12-23
24     16  201712240000 2017-12-24
25     17  201712250000 2017-12-25
26     18  201712260000 2017-12-26
27     19  201712270000 2017-12-27
28     19  201712280000 2017-12-28
29     16  201712290000 2017-12-29
..    ...           ...        ...
70     22  201710070000 2017-10-07
71     23  201710080000 2017-10-08
72     22  201710090000 2017-10-09
73     17  201710100000 2017-10-10
74     21  201710110000 2017-10-11
75     19  201710120000 2017-10-12
76     18  201710130000 2017-10-13
77     23  201710140000 2017-10-14
78     21  201710150000 2017-10-15
79     17  201710160000 2017-10-16
80     17  201710170000 2017-10-17
81     18  201710180000 2017-10-18
82     18  201710190000 2017-10-19
83     18  201710200000 2017-10-20
84     23  201710210000 2017-10-21
85     19  201710220000 2017-10-22
86     20  201710230000 2017-10-23
87     22  201710240000 2017-10-24
88     22  201710250000 2017-10-25
89     21  201710260000 2017-10-26
90     21  201710270000 2017-10-27
91     22  201710280000 2017-10-28
92     23  201710290000 2017-10-29
93     19  201708290000 2017-08-29
94     19  201708300000 2017-08-30
95     21  201708310000 2017-08-31
96     20  201709010000 2017-09-01
97     20  201709020000 2017-09-02
98     20  201709030000 2017-09-03
99     20  201709040000 2017-09-04

[100 rows x 3 columns]

In [121]:
counts_df['year'] = pd.DatetimeIndex(counts_df['Tweet_Date']).year
counts_df['month'] = pd.DatetimeIndex(counts_df['Tweet_Date']).month
counts_df['day'] =pd.DatetimeIndex(counts_df["Tweet_Date"]).day
counts_df.head()

   count    timePeriod Tweet_Date  year  month  day
0     20  201711300000 2017-11-30  2017     11   30
1     19  201712010000 2017-12-01  2017     12    1
2     21  201712020000 2017-12-02  2017     12    2
3     24  201712030000 2017-12-03  2017     12    3
4     21  201712040000 2017-12-04  2017     12    4

In [49]:
[print(tweet.generator.get("name")) for tweet in tweets[0:20]];

Twitter for Android
Google
Google
Twitter for Android
TweetDeck
Twitter for iPhone
Twitter Web Client
Twitter Web Client
Twitter for Android
Google
Twitter Web Client
Twitter for iPhone
Twitter for Android
Twitter for iPhone
Twitter for Android
Twitter for iPhone
Twitter for Android
Twitter for iPhone
Twitter for iPhone
Twitter for iPhone

In [51]:
from searchtweets import collect_results
rule = gen_rule_payload("tornado",
                        "from:breakingweather",
                        from_date="2012-01-01",
                        to_date="2017-12-31") 
print(rule)

tweets = collect_results(rule,
                         500,
                         {
                             'bearer_token':"AAAAAAAAAAAAAAAAAAAAAHJO9QAAAAAA1lq7WQQXLvjx4lLluLiFHkQ2J7s%3DjEgVHHSiliXi4wJg5xQ4yh5N2UneNteevNBkMbhcxZ7IYoJ1Vm",
                             'endpoint':"https://api.twitter.com/1.1/tweets/search/fullarchive/Plongterm.json",
                             'account_type':"premium"
                         })
[print(tweet.all_text, end='\n\n') for tweet in tweets[0:10]];

{"query": "tornado", "toDate": "201712310000", "fromDate": "201201010000"}
2811 tornado warnings were issued by local forecast offices in 2017. #weatherOf2017
Learn more about tornadoes: https://t.co/N0C7rm48ne https://t.co/G28DBrQ9e2

Sonic Unleashed (X360/PS3) | Part 40: Hub World Stuff &amp; Tornado Stage 2: https://t.co/lfjSKVS5FC via @YouTube

I added a video to a @YouTube playlist https://t.co/lfjSKVS5FC Sonic Unleashed (X360/PS3) | Part 40: Hub World Stuff &amp; Tornado Stage 2

These lads are looking forward to kicking off the 5th Anniversary year.

Join us on 22nd of April when they encounter a Tornado!

@60163_Tornado  / @midrlybutterley https://t.co/qhIDLmqPDA

2811 tornado warnings were issued by local forecast offices in 2017. #weatherOf2017
Learn more about tornadoes: https://t.co/N0C7rm48ne https://t.co/G28DBrQ9e2

When you try to grab a hold of me while on tornado mode @dAmAgEeFFeCt  https://t.co/N5oVN6LFOc

“One year out, this may be Trump’s greatest trick: His tornado of news-making has scrambled Americans’ grasp of time &amp; memory, producing...sensory overload that can make even seismic events...disappear from the collective consciousness &amp; public view.” https://t.co/pHAweJbaru

Muzikálový hit Největší showman vrazil do kin jak tornádo. Už jste ho viděli? Co na něj říkáte?
https://t.co/HLjHXuyw2T

2811 tornado warnings were issued by local forecast offices in 2017. #weatherOf2017
Learn more about tornadoes: https://t.co/N0C7rm48ne https://t.co/G28DBrQ9e2

Adicionei um vídeo a uma lista de reprodução do @YouTube https://t.co/1YIQHzVkrd CLOSE VIOLENT TORNADO SOUND !!! Coleridge, NE

In [55]:
from searchtweets import collect_results
rule = gen_rule_payload("from:breakingweather",
                        from_date="2012-01-01",
                        to_date="2017-12-31",
                        count_bucket="day",
                        results_per_call=500)
print(rule)
{"query":"from:breakingweather","toDate":"201201010000","fromDate":"201712310000","bucket":"day"}

counts = collect_results(rule,
                         500,
                         {
                             'bearer_token':"AAAAAAAAAAAAAAAAAAAAAHJO9QAAAAAA1lq7WQQXLvjx4lLluLiFHkQ2J7s%3DjEgVHHSiliXi4wJg5xQ4yh5N2UneNteevNBkMbhcxZ7IYoJ1Vm",
                             'endpoint':"https://api.twitter.com/1.1/tweets/search/fullarchive/Plongterm.json",
                             'account_type':"premium"
                         })
[print(tweet.all_text, end='\n\n') for tweet in tweets[0:10]];

[print(c) for c in counts];

{"query": "from:breakingweather", "toDate": "201712310000", "fromDate": "201201010000", "bucket": "day"}

retrying request; current status code: 429

2811 tornado warnings were issued by local forecast offices in 2017. #weatherOf2017
Learn more about tornadoes: https://t.co/N0C7rm48ne https://t.co/G28DBrQ9e2

Sonic Unleashed (X360/PS3) | Part 40: Hub World Stuff &amp; Tornado Stage 2: https://t.co/lfjSKVS5FC via @YouTube

I added a video to a @YouTube playlist https://t.co/lfjSKVS5FC Sonic Unleashed (X360/PS3) | Part 40: Hub World Stuff &amp; Tornado Stage 2

These lads are looking forward to kicking off the 5th Anniversary year.

Join us on 22nd of April when they encounter a Tornado!

@60163_Tornado  / @midrlybutterley https://t.co/qhIDLmqPDA

2811 tornado warnings were issued by local forecast offices in 2017. #weatherOf2017
Learn more about tornadoes: https://t.co/N0C7rm48ne https://t.co/G28DBrQ9e2

When you try to grab a hold of me while on tornado mode @dAmAgEeFFeCt  https://t.co/N5oVN6LFOc

“One year out, this may be Trump’s greatest trick: His tornado of news-making has scrambled Americans’ grasp of time &amp; memory, producing...sensory overload that can make even seismic events...disappear from the collective consciousness &amp; public view.” https://t.co/pHAweJbaru

Muzikálový hit Největší showman vrazil do kin jak tornádo. Už jste ho viděli? Co na něj říkáte?
https://t.co/HLjHXuyw2T

2811 tornado warnings were issued by local forecast offices in 2017. #weatherOf2017
Learn more about tornadoes: https://t.co/N0C7rm48ne https://t.co/G28DBrQ9e2

Adicionei um vídeo a uma lista de reprodução do @YouTube https://t.co/1YIQHzVkrd CLOSE VIOLENT TORNADO SOUND !!! Coleridge, NE

{'timePeriod': '201711300000', 'count': 20}
{'timePeriod': '201712010000', 'count': 19}
{'timePeriod': '201712020000', 'count': 21}
{'timePeriod': '201712030000', 'count': 24}
{'timePeriod': '201712040000', 'count': 21}
{'timePeriod': '201712050000', 'count': 25}
{'timePeriod': '201712060000', 'count': 21}
{'timePeriod': '201712070000', 'count': 23}
{'timePeriod': '201712080000', 'count': 21}
{'timePeriod': '201712090000', 'count': 24}
{'timePeriod': '201712100000', 'count': 22}
{'timePeriod': '201712110000', 'count': 22}
{'timePeriod': '201712120000', 'count': 22}
{'timePeriod': '201712130000', 'count': 19}
{'timePeriod': '201712140000', 'count': 18}
{'timePeriod': '201712150000', 'count': 19}
{'timePeriod': '201712160000', 'count': 24}
{'timePeriod': '201712170000', 'count': 22}
{'timePeriod': '201712180000', 'count': 21}
{'timePeriod': '201712190000', 'count': 18}
{'timePeriod': '201712200000', 'count': 19}
{'timePeriod': '201712210000', 'count': 20}
{'timePeriod': '201712220000', 'count': 19}
{'timePeriod': '201712230000', 'count': 22}
{'timePeriod': '201712240000', 'count': 16}
{'timePeriod': '201712250000', 'count': 17}
{'timePeriod': '201712260000', 'count': 18}
{'timePeriod': '201712270000', 'count': 19}
{'timePeriod': '201712280000', 'count': 19}
{'timePeriod': '201712290000', 'count': 16}
{'timePeriod': '201712300000', 'count': 20}
{'timePeriod': '201710300000', 'count': 18}
{'timePeriod': '201710310000', 'count': 19}
{'timePeriod': '201711010000', 'count': 20}
{'timePeriod': '201711020000', 'count': 19}
{'timePeriod': '201711030000', 'count': 21}
{'timePeriod': '201711040000', 'count': 22}
{'timePeriod': '201711050000', 'count': 24}
{'timePeriod': '201711060000', 'count': 21}
{'timePeriod': '201711070000', 'count': 21}
{'timePeriod': '201711080000', 'count': 21}
{'timePeriod': '201711090000', 'count': 21}
{'timePeriod': '201711100000', 'count': 20}
{'timePeriod': '201711110000', 'count': 22}
{'timePeriod': '201711120000', 'count': 21}
{'timePeriod': '201711130000', 'count': 22}
{'timePeriod': '201711140000', 'count': 19}
{'timePeriod': '201711150000', 'count': 13}
{'timePeriod': '201711160000', 'count': 18}
{'timePeriod': '201711170000', 'count': 18}
{'timePeriod': '201711180000', 'count': 23}
{'timePeriod': '201711190000', 'count': 23}
{'timePeriod': '201711200000', 'count': 19}
{'timePeriod': '201711210000', 'count': 15}
{'timePeriod': '201711220000', 'count': 22}
{'timePeriod': '201711230000', 'count': 19}
{'timePeriod': '201711240000', 'count': 19}
{'timePeriod': '201711250000', 'count': 24}
{'timePeriod': '201711260000', 'count': 21}
{'timePeriod': '201711270000', 'count': 18}
{'timePeriod': '201711280000', 'count': 18}
{'timePeriod': '201711290000', 'count': 16}
{'timePeriod': '201709290000', 'count': 18}
{'timePeriod': '201709300000', 'count': 20}
{'timePeriod': '201710010000', 'count': 17}
{'timePeriod': '201710020000', 'count': 18}
{'timePeriod': '201710030000', 'count': 22}
{'timePeriod': '201710040000', 'count': 19}
{'timePeriod': '201710050000', 'count': 20}
{'timePeriod': '201710060000', 'count': 17}
{'timePeriod': '201710070000', 'count': 22}
{'timePeriod': '201710080000', 'count': 23}
{'timePeriod': '201710090000', 'count': 22}
{'timePeriod': '201710100000', 'count': 17}
{'timePeriod': '201710110000', 'count': 21}
{'timePeriod': '201710120000', 'count': 19}
{'timePeriod': '201710130000', 'count': 18}
{'timePeriod': '201710140000', 'count': 23}
{'timePeriod': '201710150000', 'count': 21}
{'timePeriod': '201710160000', 'count': 17}
{'timePeriod': '201710170000', 'count': 17}
{'timePeriod': '201710180000', 'count': 18}
{'timePeriod': '201710190000', 'count': 18}
{'timePeriod': '201710200000', 'count': 18}
{'timePeriod': '201710210000', 'count': 23}
{'timePeriod': '201710220000', 'count': 19}
{'timePeriod': '201710230000', 'count': 20}
{'timePeriod': '201710240000', 'count': 22}
{'timePeriod': '201710250000', 'count': 22}
{'timePeriod': '201710260000', 'count': 21}
{'timePeriod': '201710270000', 'count': 21}
{'timePeriod': '201710280000', 'count': 22}
{'timePeriod': '201710290000', 'count': 23}
{'timePeriod': '201708290000', 'count': 19}
{'timePeriod': '201708300000', 'count': 19}
{'timePeriod': '201708310000', 'count': 21}
{'timePeriod': '201709010000', 'count': 20}
{'timePeriod': '201709020000', 'count': 20}
{'timePeriod': '201709030000', 'count': 20}
{'timePeriod': '201709040000', 'count': 20}
{'timePeriod': '201709050000', 'count': 22}
{'timePeriod': '201709060000', 'count': 22}
{'timePeriod': '201709070000', 'count': 19}
{'timePeriod': '201709080000', 'count': 22}
{'timePeriod': '201709090000', 'count': 19}
{'timePeriod': '201709100000', 'count': 27}
{'timePeriod': '201709110000', 'count': 22}
{'timePeriod': '201709120000', 'count': 17}
{'timePeriod': '201709130000', 'count': 20}
{'timePeriod': '201709140000', 'count': 19}
{'timePeriod': '201709150000', 'count': 22}
{'timePeriod': '201709160000', 'count': 22}
{'timePeriod': '201709170000', 'count': 20}
{'timePeriod': '201709180000', 'count': 21}
{'timePeriod': '201709190000', 'count': 21}
{'timePeriod': '201709200000', 'count': 22}
{'timePeriod': '201709210000', 'count': 18}
{'timePeriod': '201709220000', 'count': 19}
{'timePeriod': '201709230000', 'count': 21}
{'timePeriod': '201709240000', 'count': 23}
{'timePeriod': '201709250000', 'count': 18}
{'timePeriod': '201709260000', 'count': 19}
{'timePeriod': '201709270000', 'count': 23}
{'timePeriod': '201709280000', 'count': 16}
{'timePeriod': '201707290000', 'count': 20}
{'timePeriod': '201707300000', 'count': 22}
{'timePeriod': '201707310000', 'count': 23}
{'timePeriod': '201708010000', 'count': 19}
{'timePeriod': '201708020000', 'count': 21}
{'timePeriod': '201708030000', 'count': 21}
{'timePeriod': '201708040000', 'count': 20}
{'timePeriod': '201708050000', 'count': 20}
{'timePeriod': '201708060000', 'count': 19}
{'timePeriod': '201708070000', 'count': 14}
{'timePeriod': '201708080000', 'count': 15}
{'timePeriod': '201708090000', 'count': 13}
{'timePeriod': '201708100000', 'count': 20}
{'timePeriod': '201708110000', 'count': 18}
{'timePeriod': '201708120000', 'count': 20}
{'timePeriod': '201708130000', 'count': 17}
{'timePeriod': '201708140000', 'count': 16}
{'timePeriod': '201708150000', 'count': 19}
{'timePeriod': '201708160000', 'count': 20}
{'timePeriod': '201708170000', 'count': 18}
{'timePeriod': '201708180000', 'count': 20}
{'timePeriod': '201708190000', 'count': 21}
{'timePeriod': '201708200000', 'count': 22}
{'timePeriod': '201708210000', 'count': 50}
{'timePeriod': '201708220000', 'count': 21}
{'timePeriod': '201708230000', 'count': 20}
{'timePeriod': '201708240000', 'count': 18}
{'timePeriod': '201708250000', 'count': 26}
{'timePeriod': '201708260000', 'count': 21}
{'timePeriod': '201708270000', 'count': 28}
{'timePeriod': '201708280000', 'count': 17}
{'timePeriod': '201706280000', 'count': 18}
{'timePeriod': '201706290000', 'count': 17}
{'timePeriod': '201706300000', 'count': 18}
{'timePeriod': '201707010000', 'count': 23}
{'timePeriod': '201707020000', 'count': 23}
{'timePeriod': '201707030000', 'count': 20}
{'timePeriod': '201707040000', 'count': 18}
{'timePeriod': '201707050000', 'count': 18}
{'timePeriod': '201707060000', 'count': 18}
{'timePeriod': '201707070000', 'count': 18}
{'timePeriod': '201707080000', 'count': 22}
{'timePeriod': '201707090000', 'count': 23}
{'timePeriod': '201707100000', 'count': 17}
{'timePeriod': '201707110000', 'count': 18}
{'timePeriod': '201707120000', 'count': 19}
{'timePeriod': '201707130000', 'count': 18}
{'timePeriod': '201707140000', 'count': 19}
{'timePeriod': '201707150000', 'count': 22}
{'timePeriod': '201707160000', 'count': 22}
{'timePeriod': '201707170000', 'count': 20}
{'timePeriod': '201707180000', 'count': 20}
{'timePeriod': '201707190000', 'count': 18}
{'timePeriod': '201707200000', 'count': 24}
{'timePeriod': '201707210000', 'count': 20}
{'timePeriod': '201707220000', 'count': 18}
{'timePeriod': '201707230000', 'count': 20}
{'timePeriod': '201707240000', 'count': 22}
{'timePeriod': '201707250000', 'count': 20}
{'timePeriod': '201707260000', 'count': 18}
{'timePeriod': '201707270000', 'count': 22}
{'timePeriod': '201707280000', 'count': 18}
{'timePeriod': '201705280000', 'count': 29}
{'timePeriod': '201705290000', 'count': 18}
{'timePeriod': '201705300000', 'count': 20}
{'timePeriod': '201705310000', 'count': 19}
{'timePeriod': '201706010000', 'count': 19}
{'timePeriod': '201706020000', 'count': 18}
{'timePeriod': '201706030000', 'count': 22}
{'timePeriod': '201706040000', 'count': 22}
{'timePeriod': '201706050000', 'count': 19}
{'timePeriod': '201706060000', 'count': 18}
{'timePeriod': '201706070000', 'count': 21}
{'timePeriod': '201706080000', 'count': 17}
{'timePeriod': '201706090000', 'count': 20}
{'timePeriod': '201706100000', 'count': 22}
{'timePeriod': '201706110000', 'count': 24}
{'timePeriod': '201706120000', 'count': 22}
{'timePeriod': '201706130000', 'count': 19}
{'timePeriod': '201706140000', 'count': 19}
{'timePeriod': '201706150000', 'count': 17}
{'timePeriod': '201706160000', 'count': 21}
{'timePeriod': '201706170000', 'count': 22}
{'timePeriod': '201706180000', 'count': 21}
{'timePeriod': '201706190000', 'count': 20}
{'timePeriod': '201706200000', 'count': 18}
{'timePeriod': '201706210000', 'count': 18}
{'timePeriod': '201706220000', 'count': 20}
{'timePeriod': '201706230000', 'count': 17}
{'timePeriod': '201706240000', 'count': 22}
{'timePeriod': '201706250000', 'count': 19}
{'timePeriod': '201706260000', 'count': 21}
{'timePeriod': '201706270000', 'count': 19}
{'timePeriod': '201704270000', 'count': 19}
{'timePeriod': '201704280000', 'count': 22}
{'timePeriod': '201704290000', 'count': 24}
{'timePeriod': '201704300000', 'count': 26}
{'timePeriod': '201705010000', 'count': 21}
{'timePeriod': '201705020000', 'count': 20}
{'timePeriod': '201705030000', 'count': 19}
{'timePeriod': '201705040000', 'count': 19}
{'timePeriod': '201705050000', 'count': 20}
{'timePeriod': '201705060000', 'count': 22}
{'timePeriod': '201705070000', 'count': 22}
{'timePeriod': '201705080000', 'count': 15}
{'timePeriod': '201705090000', 'count': 15}
{'timePeriod': '201705100000', 'count': 20}
{'timePeriod': '201705110000', 'count': 19}
{'timePeriod': '201705120000', 'count': 17}
{'timePeriod': '201705130000', 'count': 20}
{'timePeriod': '201705140000', 'count': 20}
{'timePeriod': '201705150000', 'count': 17}
{'timePeriod': '201705160000', 'count': 19}
{'timePeriod': '201705170000', 'count': 20}
{'timePeriod': '201705180000', 'count': 20}
{'timePeriod': '201705190000', 'count': 19}
{'timePeriod': '201705200000', 'count': 25}
{'timePeriod': '201705210000', 'count': 22}
{'timePeriod': '201705220000', 'count': 20}
{'timePeriod': '201705230000', 'count': 18}
{'timePeriod': '201705240000', 'count': 22}
{'timePeriod': '201705250000', 'count': 17}
{'timePeriod': '201705260000', 'count': 21}
{'timePeriod': '201705270000', 'count': 24}
{'timePeriod': '201703270000', 'count': 23}
{'timePeriod': '201703280000', 'count': 18}
{'timePeriod': '201703290000', 'count': 19}
{'timePeriod': '201703300000', 'count': 19}
{'timePeriod': '201703310000', 'count': 19}
{'timePeriod': '201704010000', 'count': 20}
{'timePeriod': '201704020000', 'count': 25}
{'timePeriod': '201704030000', 'count': 19}
{'timePeriod': '201704040000', 'count': 20}
{'timePeriod': '201704050000', 'count': 23}
{'timePeriod': '201704060000', 'count': 21}
{'timePeriod': '201704070000', 'count': 19}
{'timePeriod': '201704080000', 'count': 20}
{'timePeriod': '201704090000', 'count': 22}
{'timePeriod': '201704100000', 'count': 19}
{'timePeriod': '201704110000', 'count': 19}
{'timePeriod': '201704120000', 'count': 18}
{'timePeriod': '201704130000', 'count': 19}
{'timePeriod': '201704140000', 'count': 18}
{'timePeriod': '201704150000', 'count': 21}
{'timePeriod': '201704160000', 'count': 17}
{'timePeriod': '201704170000', 'count': 18}
{'timePeriod': '201704180000', 'count': 19}
{'timePeriod': '201704190000', 'count': 18}
{'timePeriod': '201704200000', 'count': 31}
{'timePeriod': '201704210000', 'count': 20}
{'timePeriod': '201704220000', 'count': 23}
{'timePeriod': '201704230000', 'count': 19}
{'timePeriod': '201704240000', 'count': 17}
{'timePeriod': '201704250000', 'count': 21}
{'timePeriod': '201704260000', 'count': 21}
{'timePeriod': '201702240000', 'count': 24}
{'timePeriod': '201702250000', 'count': 23}
{'timePeriod': '201702260000', 'count': 18}
{'timePeriod': '201702270000', 'count': 19}
{'timePeriod': '201702280000', 'count': 18}
{'timePeriod': '201703010000', 'count': 21}
{'timePeriod': '201703020000', 'count': 24}
{'timePeriod': '201703030000', 'count': 21}
{'timePeriod': '201703040000', 'count': 23}
{'timePeriod': '201703050000', 'count': 23}
{'timePeriod': '201703060000', 'count': 20}
{'timePeriod': '201703070000', 'count': 19}
{'timePeriod': '201703080000', 'count': 21}
{'timePeriod': '201703090000', 'count': 18}
{'timePeriod': '201703100000', 'count': 19}
{'timePeriod': '201703110000', 'count': 20}
{'timePeriod': '201703120000', 'count': 20}
{'timePeriod': '201703130000', 'count': 18}
{'timePeriod': '201703140000', 'count': 23}
{'timePeriod': '201703150000', 'count': 20}
{'timePeriod': '201703160000', 'count': 20}
{'timePeriod': '201703170000', 'count': 21}
{'timePeriod': '201703180000', 'count': 21}
{'timePeriod': '201703190000', 'count': 22}
{'timePeriod': '201703200000', 'count': 19}
{'timePeriod': '201703210000', 'count': 20}
{'timePeriod': '201703220000', 'count': 19}
{'timePeriod': '201703230000', 'count': 19}
{'timePeriod': '201703240000', 'count': 19}
{'timePeriod': '201703250000', 'count': 22}
{'timePeriod': '201703260000', 'count': 27}
{'timePeriod': '201701240000', 'count': 20}
{'timePeriod': '201701250000', 'count': 21}
{'timePeriod': '201701260000', 'count': 19}
{'timePeriod': '201701270000', 'count': 20}
{'timePeriod': '201701280000', 'count': 22}
{'timePeriod': '201701290000', 'count': 23}
{'timePeriod': '201701300000', 'count': 21}
{'timePeriod': '201701310000', 'count': 18}
{'timePeriod': '201702010000', 'count': 21}
{'timePeriod': '201702020000', 'count': 23}
{'timePeriod': '201702030000', 'count': 21}
{'timePeriod': '201702040000', 'count': 20}
{'timePeriod': '201702050000', 'count': 20}
{'timePeriod': '201702060000', 'count': 19}
{'timePeriod': '201702070000', 'count': 22}
{'timePeriod': '201702080000', 'count': 20}
{'timePeriod': '201702090000', 'count': 29}
{'timePeriod': '201702100000', 'count': 21}
{'timePeriod': '201702110000', 'count': 20}
{'timePeriod': '201702120000', 'count': 20}
{'timePeriod': '201702130000', 'count': 20}
{'timePeriod': '201702140000', 'count': 19}
{'timePeriod': '201702150000', 'count': 16}
{'timePeriod': '201702160000', 'count': 19}
{'timePeriod': '201702170000', 'count': 27}
{'timePeriod': '201702180000', 'count': 20}
{'timePeriod': '201702190000', 'count': 24}
{'timePeriod': '201702200000', 'count': 21}
{'timePeriod': '201702210000', 'count': 18}
{'timePeriod': '201702220000', 'count': 19}
{'timePeriod': '201702230000', 'count': 41}
{'timePeriod': '201612240000', 'count': 22}
{'timePeriod': '201612250000', 'count': 25}
{'timePeriod': '201612260000', 'count': 19}
{'timePeriod': '201612270000', 'count': 18}
{'timePeriod': '201612280000', 'count': 20}
{'timePeriod': '201612290000', 'count': 19}
{'timePeriod': '201612300000', 'count': 25}
{'timePeriod': '201612310000', 'count': 20}
{'timePeriod': '201701010000', 'count': 21}
{'timePeriod': '201701020000', 'count': 19}
{'timePeriod': '201701030000', 'count': 20}
{'timePeriod': '201701040000', 'count': 22}
{'timePeriod': '201701050000', 'count': 24}
{'timePeriod': '201701060000', 'count': 21}
{'timePeriod': '201701070000', 'count': 22}
{'timePeriod': '201701080000', 'count': 29}
{'timePeriod': '201701090000', 'count': 20}
{'timePeriod': '201701100000', 'count': 20}
{'timePeriod': '201701110000', 'count': 19}
{'timePeriod': '201701120000', 'count': 19}
{'timePeriod': '201701130000', 'count': 30}
{'timePeriod': '201701140000', 'count': 25}
{'timePeriod': '201701150000', 'count': 22}
{'timePeriod': '201701160000', 'count': 20}
{'timePeriod': '201701170000', 'count': 20}
{'timePeriod': '201701180000', 'count': 21}
{'timePeriod': '201701190000', 'count': 21}
{'timePeriod': '201701200000', 'count': 19}
{'timePeriod': '201701210000', 'count': 28}
{'timePeriod': '201701220000', 'count': 26}
{'timePeriod': '201701230000', 'count': 21}
{'timePeriod': '201611230000', 'count': 19}
{'timePeriod': '201611240000', 'count': 21}
{'timePeriod': '201611250000', 'count': 18}
{'timePeriod': '201611260000', 'count': 18}
{'timePeriod': '201611270000', 'count': 20}
{'timePeriod': '201611280000', 'count': 18}
{'timePeriod': '201611290000', 'count': 21}
{'timePeriod': '201611300000', 'count': 19}
{'timePeriod': '201612010000', 'count': 18}
{'timePeriod': '201612020000', 'count': 17}
{'timePeriod': '201612030000', 'count': 20}
{'timePeriod': '201612040000', 'count': 22}
{'timePeriod': '201612050000', 'count': 20}
{'timePeriod': '201612060000', 'count': 18}
{'timePeriod': '201612070000', 'count': 20}
{'timePeriod': '201612080000', 'count': 19}
{'timePeriod': '201612090000', 'count': 19}
{'timePeriod': '201612100000', 'count': 21}
{'timePeriod': '201612110000', 'count': 23}
{'timePeriod': '201612120000', 'count': 19}
{'timePeriod': '201612130000', 'count': 20}
{'timePeriod': '201612140000', 'count': 19}
{'timePeriod': '201612150000', 'count': 19}
{'timePeriod': '201612160000', 'count': 21}
{'timePeriod': '201612170000', 'count': 24}
{'timePeriod': '201612180000', 'count': 25}
{'timePeriod': '201612190000', 'count': 20}
{'timePeriod': '201612200000', 'count': 18}
{'timePeriod': '201612210000', 'count': 19}
{'timePeriod': '201612220000', 'count': 20}
{'timePeriod': '201612230000', 'count': 17}
{'timePeriod': '201610230000', 'count': 23}
{'timePeriod': '201610240000', 'count': 20}
{'timePeriod': '201610250000', 'count': 22}
{'timePeriod': '201610260000', 'count': 19}
{'timePeriod': '201610270000', 'count': 21}
{'timePeriod': '201610280000', 'count': 20}
{'timePeriod': '201610290000', 'count': 20}
{'timePeriod': '201610300000', 'count': 17}
{'timePeriod': '201610310000', 'count': 21}
{'timePeriod': '201611010000', 'count': 19}
{'timePeriod': '201611020000', 'count': 19}
{'timePeriod': '201611030000', 'count': 22}
{'timePeriod': '201611040000', 'count': 18}
{'timePeriod': '201611050000', 'count': 18}
{'timePeriod': '201611060000', 'count': 17}
{'timePeriod': '201611070000', 'count': 19}

In [122]:
import pandas as pd

counts_df = pd.DataFrame(counts)

counts_df.head(1000)

counts_df["Tweet_Date"] = pd.to_datetime(counts_df["timePeriod"], format="%Y%m%d%H%M", errors='ignore')

counts_df.head(100)

    count    timePeriod Tweet_Date
0      20  201711300000 2017-11-30
1      19  201712010000 2017-12-01
2      21  201712020000 2017-12-02
3      24  201712030000 2017-12-03
4      21  201712040000 2017-12-04
5      25  201712050000 2017-12-05
6      21  201712060000 2017-12-06
7      23  201712070000 2017-12-07
8      21  201712080000 2017-12-08
9      24  201712090000 2017-12-09
10     22  201712100000 2017-12-10
11     22  201712110000 2017-12-11
12     22  201712120000 2017-12-12
13     19  201712130000 2017-12-13
14     18  201712140000 2017-12-14
15     19  201712150000 2017-12-15
16     24  201712160000 2017-12-16
17     22  201712170000 2017-12-17
18     21  201712180000 2017-12-18
19     18  201712190000 2017-12-19
20     19  201712200000 2017-12-20
21     20  201712210000 2017-12-21
22     19  201712220000 2017-12-22
23     22  201712230000 2017-12-23
24     16  201712240000 2017-12-24
25     17  201712250000 2017-12-25
26     18  201712260000 2017-12-26
27     19  201712270000 2017-12-27
28     19  201712280000 2017-12-28
29     16  201712290000 2017-12-29
..    ...           ...        ...
70     22  201710070000 2017-10-07
71     23  201710080000 2017-10-08
72     22  201710090000 2017-10-09
73     17  201710100000 2017-10-10
74     21  201710110000 2017-10-11
75     19  201710120000 2017-10-12
76     18  201710130000 2017-10-13
77     23  201710140000 2017-10-14
78     21  201710150000 2017-10-15
79     17  201710160000 2017-10-16
80     17  201710170000 2017-10-17
81     18  201710180000 2017-10-18
82     18  201710190000 2017-10-19
83     18  201710200000 2017-10-20
84     23  201710210000 2017-10-21
85     19  201710220000 2017-10-22
86     20  201710230000 2017-10-23
87     22  201710240000 2017-10-24
88     22  201710250000 2017-10-25
89     21  201710260000 2017-10-26
90     21  201710270000 2017-10-27
91     22  201710280000 2017-10-28
92     23  201710290000 2017-10-29
93     19  201708290000 2017-08-29
94     19  201708300000 2017-08-30
95     21  201708310000 2017-08-31
96     20  201709010000 2017-09-01
97     20  201709020000 2017-09-02
98     20  201709030000 2017-09-03
99     20  201709040000 2017-09-04

[100 rows x 3 columns]

In [123]:
counts_df['year'] = pd.DatetimeIndex(counts_df['Tweet_Date']).year
counts_df['month'] = pd.DatetimeIndex(counts_df['Tweet_Date']).month
counts_df['day'] =pd.DatetimeIndex(counts_df["Tweet_Date"]).day
counts_df.head()

   count    timePeriod Tweet_Date  year  month  day
0     20  201711300000 2017-11-30  2017     11   30
1     19  201712010000 2017-12-01  2017     12    1
2     21  201712020000 2017-12-02  2017     12    2
3     24  201712030000 2017-12-03  2017     12    3
4     21  201712040000 2017-12-04  2017     12    4